apiVersion: v1
kind: Secret
metadata:
    name: smth
    namespace: default
stringData:
    smth: ENC[AES256_GCM,data:UGzASg==,iv:Jk0v9wngy7Jos6AnIMPjpcDTJzAJZ10GVu8lDGGr3aw=,tag:KzXndvXcW6z2Z4AmfbyG4w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:457472006214:key/05b81b6d-88e7-4abe-b139-155221ace2cd
          created_at: "2022-04-30T08:04:00Z"
          enc: AQICAHhD4yYhu2hKT/TcH3J9ZyLQzzkgb95HP9q7s9eEty73bAETPlZ8vdd6ucmgH/fE3nHsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmByebdCMRa9ozIatAgEQgDtrzfgVME7JBaDPFlTIfIj5JhckgSx+60ZnQRsXays7clbn5dPKcDEqJkZStk2LEIvPdGIkezYfw1i43Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-30T08:04:01Z"
    mac: ENC[AES256_GCM,data:5NCGsEH5EK9KAhOGD9iyRe8ka8B8m/P86kCKWaKoQ71ZSDMNirzzF17vVWLpPQkG3Q0zabAKYqZcKJLcHPd9wKOPn8r8CgEEJBf+pa9l3ICYEk/apjBNZgLEz41EvelqcdOTDdjCcpxiCnO7JvMZiEgC7acTppWTy7nOFNKfXW8=,iv:dTH+JEy1oQDl/ykyxqNY1tEujy2t3vkivW9ZxxRVZoQ=,tag:PRR7By81HyOd1lWOIgRaBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
